[phases.setup]
aptPkgs = [
    "cmake",
    "libx11-6",
    "libgl1-mesa-glx",
    "libglib2.0-0",
    "libsm6",
    "libxext6",
    "libxrender-dev",
    "python3-dev",
    "gcc"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"